[2023-05-24T12:43:36.882+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: docker-dag.create_table manual__2023-05-24T12:43:36.295112+00:00 [queued]>
[2023-05-24T12:43:36.889+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: docker-dag.create_table manual__2023-05-24T12:43:36.295112+00:00 [queued]>
[2023-05-24T12:43:36.889+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T12:43:36.890+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-05-24T12:43:36.890+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-24T12:43:36.898+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_table> on 2023-05-24 12:43:36.295112+00:00
[2023-05-24T12:43:36.903+0000] {standard_task_runner.py:55} INFO - Started process 1323 to run task
[2023-05-24T12:43:36.906+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'docker-dag', 'create_table', 'manual__2023-05-24T12:43:36.295112+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/docker-task.py', '--cfg-path', '/tmp/tmp17jnrm43']
[2023-05-24T12:43:36.907+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask create_table
[2023-05-24T12:43:36.960+0000] {task_command.py:388} INFO - Running <TaskInstance: docker-dag.create_table manual__2023-05-24T12:43:36.295112+00:00 [running]> on host fe8636e26e35
[2023-05-24T12:43:37.010+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker-dag
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-05-24T12:43:36.295112+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-24T12:43:36.295112+00:00
[2023-05-24T12:43:37.012+0000] {sql.py:254} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS test(
                time varchar(255) not null
            );
        
[2023-05-24T12:43:37.021+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-24T12:43:37.134+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-05-24T12:43:37.148+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "***" to address: Name or service not known

[2023-05-24T12:43:37.162+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=docker-dag, task_id=create_table, execution_date=20230524T124336, start_date=20230524T124336, end_date=20230524T124337
[2023-05-24T12:43:37.202+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task create_table (could not translate host name "***" to address: Name or service not known
; 1323)
[2023-05-24T12:43:37.239+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-05-24T12:43:37.254+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
